=== adumitol/LLMM/Tema 5/ValidacionXML/ejemplo3/assets/ejemplo3.dtd
<!ELEMENT restaurante (menu, recetas, clientes)>
<!ELEMENT menu (platos)>
<!ELEMENT platos (plato+)>
<!ELEMENT plato (nombre, categoria, lista_ingredientes, precio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT lista_ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT lista_ingredientes1 (ingrediente1+)>
<!ELEMENT ingrediente1 (nombre)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT recetas (receta+)>
<!ELEMENT receta (nombre, lista_ingredientes1, pasos)>
<!ELEMENT pasos (paso+)>
<!ELEMENT paso (#PCDATA)>
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombre, telefono, email, pedidos)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido (fecha, platos1)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT platos1 (plato1+)>
<!ELEMENT plato1 (#PCDATA)>
<!ATTLIST recetas comensales (adultos | niÃ±os) #REQUIRED>
<!ATTLIST precio moneda (USD | EUR | GBP) #REQUIRED>
<!ATTLIST ingrediente1 cantidad CDATA #IMPLIED>

=== adumitol/LLMM/Tema 5/ValidacionXML/ejemplo3/ejemplo3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurante SYSTEM "./assets/ejemplo3.dtd">

<restaurante>
    <menu>
        <platos>
            <plato>
                <nombre>Ensalada César</nombre>
                <categoria>Entrada</categoria>
                <lista_ingredientes>
                    <ingrediente>Lechuga romana</ingrediente>
                    <ingrediente>Queso parmesano</ingrediente>
                    <ingrediente>Picatostes</ingrediente>
                    <ingrediente>Salsa César</ingrediente>
                </lista_ingredientes>
                <precio moneda="EUR">8.50</precio>
            </plato>
        </platos>
    </menu>
    <recetas comensales="adultos">
        <receta>
            <nombre>Ensalada César</nombre>
            <lista_ingredientes1>
                <ingrediente1 cantidad="200g">
                    <nombre>Lechuga romana</nombre>
                </ingrediente1>
                <ingrediente1 cantidad="100g">
                    <nombre>Queso parmesano</nombre>
                </ingrediente1>
                <ingrediente1 cantidad="50g">
                    <nombre>Picatostes</nombre>
                </ingrediente1>
                <ingrediente1 cantidad="100ml">
                    <nombre>Salsa César</nombre>
                </ingrediente1>
            </lista_ingredientes1>
            <pasos>
                <paso>Lavar y cortar la lechuga.</paso>
                <paso>Rallar el queso parmesano.</paso>
                <paso>Mezclar todos los ingredientes en un bol.</paso>
                <paso>Agregar la salsa y servir.</paso>
            </pasos>
        </receta>
    </recetas>
    <clientes>
        <cliente>
            <nombre>Juan Pérez</nombre>
            <telefono>+34 600 123 456</telefono>
            <email>juan.perez@example.com</email>
            <pedidos>
                <pedido>
                    <fecha>2025-03-25</fecha>
                    <platos1>
                        <plato1>Ensalada César</plato1>
                    </platos1>
                </pedido>
            </pedidos>
        </cliente>
    </clientes>
</restaurante>
